//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starbucks.BaristaServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Hermes.Messaging.Wcf", ConfigurationName="BaristaServiceProxy.CommandService")]
    public interface CommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Hermes.Messaging.Wcf/CommandService/Execute", ReplyAction="Hermes.Messaging.Wcf/CommandService/ExecuteResponse")]
        int Execute(Starbucks.Messages.OrderCoffee command);
        
        [System.ServiceModel.OperationContractAttribute(Action="Hermes.Messaging.Wcf/CommandService/Execute", ReplyAction="Hermes.Messaging.Wcf/CommandService/ExecuteResponse")]
        System.Threading.Tasks.Task<int> ExecuteAsync(Starbucks.Messages.OrderCoffee command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommandServiceChannel : Starbucks.BaristaServiceProxy.CommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandServiceClient : System.ServiceModel.ClientBase<Starbucks.BaristaServiceProxy.CommandService>, Starbucks.BaristaServiceProxy.CommandService {
        
        public CommandServiceClient() {
        }
        
        public CommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Execute(Starbucks.Messages.OrderCoffee command) {
            return base.Channel.Execute(command);
        }
        
        public System.Threading.Tasks.Task<int> ExecuteAsync(Starbucks.Messages.OrderCoffee command) {
            return base.Channel.ExecuteAsync(command);
        }
    }
}
